### ISSUE TITLE
Question : open source or open data

### ISSUE THREAD

**Issue by kaceo** [alexvicegrab/tangoLyricsDB#6]
First I want to say Great job Alex, I love the idea of this project.

Next I want to clarify is this project just Open Source (the web and database codes), or is this project also aiming to generate Open Data?  If the latter, maybe some kind of API or export function should be added into the code.

I envisage that many Tango teachers would love to have an easy way to embed a song's lyrics (+ translations) into their blogs, but this cannot happen if there is no programmatic way to look up data via API.

Also Alex -- how about modify the code to be a Tango Festival database?  That gets a lot of activity compared to Song lyrics.

**Comment by alexvicegrab** [comment]
Hi Kaceo,
Thanks :)
The Open Data is interesting point. But there are 2 challenges:
1) I'd need to see actual demand from Tango teachers before taking on the effort of adding an API nobody will use.
2) The database is merely a way of centralising all the locations of lyrics translations, and as such is not a data repository for the translations themselves.

Regarding the Tango Festival database, there is one already at Tango Marathon Directory by Daniel De Kay, which also has Encuentros and Festivals there.

But... there may be another Tango-related database in the works...

Thanks for your feedback and suggestions!

**Comment by kaceo** [comment]
Yes I know there are already clusters of festival data being published in 4-5 websiites but none are open source, and each creates a data silo incompatible with the other. 

An open source orientation is II think more important to serve as a foundation for collaboration.

**Comment by alexvicegrab** [comment]
Good point, @kaceo, I am currently working on another small tango-related project, but once I get enough expertise in Web Development to tackle a bigger project, I might dive into that space.

**Comment by alexvicegrab** [comment]
Won't have the time or inclination to implement an API in the near or mid future, but anyone who wishes to provide a PR and enhance this project is welcome.
